[colors.bright]
black = "0x666666"
blue = "0x6699cc"
cyan = "0x66cccc"
green = "0x99cc99"
magenta = "0xcc99cc"
red = "0xff6666"
white = "0xffffff"
yellow = "0xffcc66"

[colors.normal]
black = "0x1e1e1e"
blue = "0x81a2be"
cyan = "0x8abeb7"
green = "0xb5bd68"
magenta = "0xb294bb"
red = "0xcc6666"
white = "0xeeeeee"
yellow = "0xf0c674"

[colors.primary]
background = "0x1e1e1e"
foreground = "#feffbf"

[font]
size = 9.0

[font.bold]
family = "DaddyTimeMono Nerd Font Mono"
style = "Bold"

[font.normal]
family = "DaddyTimeMono Nerd Font Mono"
style = "Regular"
[window.padding]
x = 10
y = 10
