enc_id = '00FnoQrBVL2eQfP+7SltyjvwEw18ES2HP4Wvg='
password = ''
salt = 'k4ca7d'
key_pair = [
    [
    167,
    77,
    82,
    172,
    106,
    169,
    132,
    219,
    41,
    108,
    51,
    82,
    200,
    147,
    159,
    121,
    253,
    25,
    82,
    30,
    83,
    77,
    186,
    30,
    195,
    162,
    31,
    124,
    215,
    167,
    65,
    22,
    231,
    217,
    2,
    12,
    24,
    136,
    56,
    69,
    201,
    63,
    42,
    8,
    247,
    242,
    82,
    185,
    85,
    31,
    0,
    149,
    203,
    183,
    6,
    169,
    159,
    83,
    98,
    140,
    208,
    49,
    26,
    129,
],
    [
    231,
    217,
    2,
    12,
    24,
    136,
    56,
    69,
    201,
    63,
    42,
    8,
    247,
    242,
    82,
    185,
    85,
    31,
    0,
    149,
    203,
    183,
    6,
    169,
    159,
    83,
    98,
    140,
    208,
    49,
    26,
    129,
],
]
key_confirmed = true

[keys_confirmed]
rs-ny = true
